# Tema 1 - Matrices

Vamos a ver cómo crear una matriz utilizando la librería `numpy`.

In [2]:
row = [1, 2, 3]
row

[1, 2, 3]

In [3]:
col = [[1],[2],[3]]
col

[[1], [2], [3]]

In [4]:
M = [[1,2,3], [4,5,6], [7,8,9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
M[1][1]

5

In [6]:
M[0][0]

1

In [7]:
M[0]

[1, 2, 3]

In [10]:
import numpy as np

In [16]:
M = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype = float)

In [48]:
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [53]:
M[0]

array([1., 2., 3.])

In [52]:
for row in M:
    print(row[0])

1.0
4.0
7.0


In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.shape(M)

(3, 3)

In [26]:
A = np.array([[1,2], [3,4]])
print(A)
B = np.array([[3,0], [1,-1]])
print(B)

[[1 2]
 [3 4]]
[[ 3  0]
 [ 1 -1]]


In [28]:
print(A+B)

[[4 2]
 [4 3]]


In [27]:
print(A.dot(B))

[[ 5 -2]
 [13 -4]]


In [30]:
print(A.transpose())

[[1 3]
 [2 4]]


In [31]:
print(A.trace())

5


In [34]:
np.linalg.matrix_rank(A)

2

In [35]:
np.linalg.matrix_power(A, 5)

array([[1069, 1558],
       [2337, 3406]])

In [36]:
np.linalg.det(A)

-2.0000000000000004

In [37]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [39]:
print(np.linalg.inv(A).dot(A))

[[ 1.00000000e+00  4.44089210e-16]
 [-5.55111512e-17  1.00000000e+00]]


In [40]:
X = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [41]:
np.linalg.det(X)

-9.51619735392994e-16

In [42]:
np.linalg.matrix_rank(X)

2

In [46]:
np.linalg.inv(X)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

No se nos ocurrirá nunca hacer la inversa ni de una matriz cuadrada, ni de una matriz cuyo rango sea inferior a su orden (el número de filas / columnas de la misma).

In [47]:
# np.linalg.inv(np.array([[1,2,3],[4,5,6]]))